### ISSUE TITLE
Add ability to fill wivs with background color

### ISSUE THREAD

**Issue by bendemeyer** [jjkaufman/wiv.js#27]

**Comment by jjkaufman** [comment]
A champions issue! 

I got it working over the weekend but was not satisfied with the implementation. My attempt required a second canvas to be inserted at the bottom of the wiv element dedicated to fill, z indexing was a mess

**Comment by bendemeyer** [comment]
I think I have this working. But yet again it would conflict with another open PR so I'm waiting until that's settled to open a PR.

**Comment by jjkaufman** [comment]
now supported in master
