### ISSUE TITLE
Calculate true intersection of wiggles 

### ISSUE THREAD

**Issue by jjkaufman** [jjkaufman/wiv.js#6]
Currently the intersection of wiggles is approximated and a straight "lineTo" connects the wiggles. Ideally, the true wiggle intersection can be calculated and the lineTo can be eliminated.

**Comment by jjkaufman** [comment]
The wiggles could be connected using a rotation strategy as well

**Comment by bendemeyer** [comment]
This issue resolved with PR #24: https://github.com/jjkaufman/wiv.js/pull/24
